### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/chatty-alpha-lotr#2]
## User Story
As a user, when I navigate to your site, I should see a navbar.

## AC
**Given** A user navigates to your page
**Then** they should see a navbar
**And** it should have an application logo
**And** it should have an input field
**And** it should have a clear button
**And** it should remain at the top of the screen if the page scrolls

## Dev Notes
the navbar will use the above commented above for the logo, and then should have an input and clear button as displayed in the wireframe

![image](https://user-images.githubusercontent.com/42584830/84097730-f78e2f80-a9ca-11ea-8851-2091b5f58230.png)

* The input box should have a keyup event listener checking for the enter key. On pressing enter it should send the input to the function used to add messages to the array. #14  
* The clear button functionality is described in #15

**Comment by JeremiahV93** [comment]
https://en.wikipedia.org/wiki/One_Ring#/media/File:Unico_Anello.png

**Comment by spotmonk** [comment]
the navbar will use the above commented above for the logo, and then should have an input and clear button as displayed in the wireframe

![image](https://user-images.githubusercontent.com/42584830/84097730-f78e2f80-a9ca-11ea-8851-2091b5f58230.png)


* The input box should have a keyup event listener checking for the enter key. On pressing enter it should send the input to the function used to add messages to the array. #14  
* The clear button functionality is described in #15
