### ISSUE TITLE
Seed Data

### ISSUE THREAD

**Issue by luketlancaster** [nss-evening-cohort-12/chatty-alpha-lotr#4]
## User Story
As a developer, in order to have something on the page, I would like some seed data

## AC
**Given** A developer navigated to your repo
**Then** they should see a file called `helpers/data/messageData.js`
**And** this file should have seed data for 5 messages

## Dev Notes
the messageData.js file will have a "messages" array with 5 pre-generated comments with  the following format:

```
[
     userID:
     timestamp:
     message:
     id:
]
```
data will be accessible with a getter function:
`const getMessages = () => messages`

**Comment by spotmonk** [comment]
the messageData.js file will have a "messages" array with 5 pre-generated comments with  the following format:

```
[
     user:
     timestamp:
     message:
     id:
]
```
